epochs: 50
num_workers: 4
batch_size: 1

model: "unet3d"
in_channel: 4
mid_channel: 32
out_channel: 4

optimizer: "adamw"
lr: 0.0002
wd: 0.00001

scheduler: "CosineWarmupRestarts"
cosine_T_0: 10
cosine_T_mult: 2
cosine_eta_min: 1e-6
cosine_T_max: 200

fusion_flag: true

total_parms: null
early_stop_patience: 0
resume: null
loss: "diceloss"

save_max: 5
interval: 1
optimizer: "adamw"

reduce_patience: 3
reduce_factor: 0.9
tb: true
data_split: false

# 地址
root: "/mnt/d/AI_Research/WS-HUB/Linux-VoxelMedix/VoxelMedix"
data_root: "/mnt/d/AI_Research/WS-HUB/Linux-VoxelMedix/VoxelMedix/data"

train_csv: "/mnt/d/AI_Research/WS-HUB/Linux-VoxelMedix/VoxelMedix/data/raw/brats21_original/train.csv"
val_csv: "/mnt/d/AI_Research/WS-HUB/Linux-VoxelMedix/VoxelMedix/data/raw/brats21_original/val.csv"
test_csv: "/mnt/d/AI_Research/WS-HUB/Linux-VoxelMedix/VoxelMedix/data/raw/brats21_original/test.csv"

local_train: True
train_length: 100
val_length: 20

results_root: "/mnt/d/AI_Research/WS-HUB/Linux-VoxelMedix/VoxelMedix/results"

commit: "debug"