epochs: 10
nw: 4
bs: 1
model: "fm_unet3d_dilation_fusion"
fusion_flag: true
input_channels: 4
output_channels: 4
total_parms: null
early_stop_patience: 0
resume: null
loss: "DiceLoss"
loss_type: "subarea_mean"
save_max: 5
interval: 1
optimizer: "AdamW"
lr: 3e-4
wd: 1e-5
scheduler: "CosineAnnealingLR"
cosine_min_lr: 1e-8
cosine_T_max: 300
reduce_patience: 3
reduce_factor: 0.9
tb: true
data_split: false
ts: 0.8
vs: 0.1
data_root: "./brats21_local"
data_scale: "debug"
trainSet_len: 100
valSet_len: 12
trainCropSize: [128, 128, 128]
valCropSize: [128, 128, 128]
results_root: "./results"
commit: "debug"