training:
  epochs: 10
  batch_size: 2
  num_workers: 8
  early_stop_patience: 0
  save_max: 5
  interval: 1
  tb: true
  data_split: false
  local: true
  train_length: 10
  val_length: 2
  test_length: 2

model:
  name: "unetr"
  in_channel: 4
  mid_channel: 32
  out_channel: 4
  fusion_flag: true
  total_parms: null

optimizer:
  type: "adamw"
  lr: 0.0001
  wd: 0.00001
  reduce_patience: 3
  reduce_factor: 0.9

scheduler:
  type: "CosineWarmupRestarts"
  cosine_T_0: 10
  cosine_T_mult: 2
  cosine_eta_min: 1e-6
  cosine_T_max: 200

loss:
  type: "diceloss"

paths:
  root: "/root/workspace/VoxelMedix"
  data_root: "/root/workspace/VoxelMedix/data"
  output: "/root/workspace/VoxelMedix/output"
  train_csv: "/root/workspace/VoxelMedix/data/raw/brats21_original/train.csv"
  val_csv: "/root/workspace/VoxelMedix/data/raw/brats21_original/val.csv"
  test_csv: "/root/workspace/VoxelMedix/data/raw/brats21_original/test.csv"
  results_root: "/root/workspace/VoxelMedix/results"

commit: "debug"