epochs: 100
num_workers: 8
batch_size: 2

model: "cadi_unet3d"
in_channel: 4
mid_channel: 32
out_channel: 4

optimizer: "adamw"
lr: 0.0002
wd: 0.00001

scheduler: "CosineWarmupRestarts"
cosine_T_0: 10
cosine_T_mult: 2
cosine_eta_min: 1e-6
cosine_T_max: 200

fusion_flag: true

total_parms: null
early_stop_patience: 0
resume: null
loss: "diceloss"

save_max: 5
interval: 1
optimizer: "adamw"

reduce_patience: 3
reduce_factor: 0.9
tb: true
data_split: false

# 地址
root: "/root/workspace/VoxelMedix"
data_root: "/root/workspace/VoxelMedix/data"

train_csv: "/root/workspace/VoxelMedix/data/raw/brats21_original/train.csv"
val_csv: "/root/workspace/VoxelMedix/data/raw/brats21_original/val.csv"
test_csv: "/root/workspace/VoxelMedix/data/raw/brats21_original/test.csv"

local_train: True
train_length: 500
val_length: 100

results_root: "/root/workspace/VoxelMedix/results"

commit: "debug"